name    'lab42-foo'
version '2.0.3'
author  'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source  'https://github.com/example42/puppet-foo'
summary 'Puppet module for foo'
description 'This module installs and manages foo. Check README for details. Puppi, monitor and firewall dependencies are needed only if the relevant features are enabled'
dependency 'lab42/stdlib42', '>= 2.0.0'
dependency 'lab42/puppi', '>= 2.0.0'
dependency 'lab42/monitor', '>= 2.0.0'
dependency 'lab42/firewall', '>= 2.0.0'
