name    'lab42-monitor'
version '2.0.0'
author  'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
summary 'Puppet monitoring abstraction meta module'
description 'This module provides abstraction defines to monitroing resources managed by Puppet. It's used in the Example42 modules set but can be imported and used in other setups'
dependency 'puppetlabs/stdlib', '>= 0.1.0'
dependency 'lab42/stdlib42', '>= 2.0.0'
